---
title: "Esports Data"
author: "Zoey Meng"
date: "11/12/2021"
output: html_document
---

```{r}
HED <- read.csv("HistoricalEsportData.csv")
View(HED)
library(ggplot2)
library (dplyr)
```


```{r}
game_vec <- as.vector(HED$Game)
player_vec <- as.vector(HED$Players)
tournaments_vec <- as.vector(HED$Tournaments)
earnings_vec <- as.vector(HED$Earnings)
date_vec <- as.vector(HED$Date)
```


```{r}
total_players <- tapply(player_vec, game_vec, sum)
total_players["Quake II"]
```


```{r}
total_players[which(total_players == max(total_players))]
```


```{r}
sorted_players <- sort(total_players)
tail(sorted_players, 5)
```


```{r}
total_earnings <- tapply(earnings_vec, game_vec, sum)
total_earnings[which(total_earnings == max(total_earnings))]
```


```{r}
sorted_players <- sort(total_players)
tail(sorted_players, 10)

topten_playerbase = tail(sorted_players,10)
```
```{r}
player_count = c(72132, 33603, 22618, 17214, 16569, 14765, 12491, 9505, 9135, 8975)
games = c("CS:GO", "League", "Dota 2", "StarCraft II", "CS", "Fortnite", "Overwatch", "PUBG", "Rocket League", "Super Smash")

par(mar=c(5,7,4,2)+0.1)

barplot(player_count, names.arg = games, 
        xlab = "Pro Playerbase Count",
        col = rgb(0.2,0.4,0.6,0.6), 
        horiz = T, las = 1,
        cex.names = .8,
        cex.axis = 0.8, 
        cex.lab = 1,
        xlim = c(0,80000))

title("Top 10 Games Pro Playerbase Count", adj = 0.3, line = 1)

title(ylab = "Games", mgp = c(5, 1, 0))

```



```{r}
total_earnings <- tapply(earnings_vec, game_vec, sum)
total_earnings["Counter-Strike: Global Offensive"]

sorted_earnings = sort(total_earnings)
tail(sorted_earnings, 10)
```

```{r}
earnings = c(236125713, 121845848, 108281356, 86902779, 35672680, 34789486, 33747828, 28529882, 25674831, 19157965)/1000000
games = c("Dota 2", "CS:GO", "Fortnite", "League", "Starcraft II", "Arena of Valor", "PUBG", "Overwatch", "Hearthstone", "Rainbow Six")

par(mar=c(5,7,4,2)+0.1)

barplot(earnings, names.arg = games, 
        xlab = "Total Prize Pool in Millions",
        col = rgb(0.2,0.4,0.6,0.6),
        cex.names = .8,
        cex.axis = 0.8, 
        cex.lab = 1,
        horiz = T, las = 1,
        xlim = c(0,250))


title("Top 10 Games Prize Pool", adj = 0.3, line = 1)
title(ylab = "Games", mgp = c(6, 1, 0))
```

```{R}
library(stringi)
year = c()
for(i in HED$Date){
  year = stri_sub(HED$Date, 1, 4)
}

HED$Year = as.numeric(year)

game_2020 = data.frame(HED[HED$Year == 2020, ])
game_2021 = data.frame(HED[HED$Year == 2021, ])
```

```{R}
later_proplayer = c(1823, 1032, 558, 342, 256, 225, 205, 198, 196, 175)
later_games = c("Counter-Strike", "CS:Source", "StarCraft II", "Team Fortress 2", "SSBM", "Halo 3", "StarCraft: BW", "WarCraft III", "DotA", "COD 4")

par(mar=c(5,7,4,2)+0.1)

barplot(later_proplayer, names.arg = later_games, 
        xlab = "Pro Playerbase Count",
        col = "lightskyblue", 
        horiz = T, las = 1,
        cex.names = .8,
        cex.axis = 0.8, 
        cex.lab = 1,
        xlim = c(0,2000))

title("Top 10 Games of 2010 \nPro Playerbase Count", adj = 0.3, line = 1)
title(ylab = "Games", mgp = c(6, 1, 0))
```
```{R}
recent_proplayer = c(8762, 3669, 3618, 3075, 3008, 2952, 2655, 1922, 1610, 1203)
recent_games = c("CS:GO", "Fortnite", "Valorant", "League", "Dota 2", "PUBG", "Rocket League", "Apex Legends", "Six Siege", "COD: Warzone")

par(mar=c(5,7,4,2)+0.1)

barplot(recent_proplayer, names.arg = recent_games, 
        xlab = "Pro Playerbase Count",
        col = "mediumpurple1", 
        horiz = T, las = 1,
        cex.names = .8,
        cex.axis = 0.8, 
        cex.lab = 1,
        xlim = c(0,10000))

title("Top 10 Games of 2020 \nPro Playerbase Count", adj = 0.3, line = 1)
title(ylab = "Games", mgp = c(6, 1, 0))
```

```{R}
later_prizepool = c(454363, 431022, 338168, 290007, 244414, 225226, 221381, 218835, 215095, 190624)/1000
later_games = c("Halo 3", "CS:Source", "TrackMania:NF", "CS", "SSBB", "WarCraft III", "FIFA 10", "iRacing.com", "COD 4", "Quake Live")

par(mar=c(5,7,4,2)+0.1)

barplot(later_prizepool, names.arg = later_games, 
        xlab = "Prize Pool in Thousands",
        col = "lightskyblue", 
        horiz = T, las = 1,
        cex.names = .8,
        cex.axis = 0.8, 
        cex.lab = 1,
        xlim = c(0, 500))

title("10 Largest Games by Prizepool in 2010", adj = 0.3, line = 1)
title(ylab = "Games", mgp = c(5.5, 1, 0))
```

```{R}
recent_prizepool = c(15943485, 9500997, 9372569, 8876401, 8466911, 7152172, 6492507, 5859298, 5763561, 5101127)/1000000
recent_games = c("CS:GO", "Arena of Valor", "Dota 2", "Fortnite", "League", "COD:MW", "PUBG Mobile", "Six Siege", "Overwatch", "PUBG")

par(mar=c(5,7,4,2)+0.1)

barplot(recent_prizepool, names.arg = recent_games, 
        xlab = "Prize Pool in Millions",
        col = "mediumpurple1", 
        horiz = T, las = 1,
        cex.names = .8,
        cex.axis = 0.8, 
        cex.lab = 1,
        xlim = c(0, 20))

title("10 Largest Games by Prizepool in 2020", adj = 0.3, line = 1)
title(ylab = "Games", mgp = c(5.5, 1, 0))
```